name: STM32 Build

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        build_type: [Debug, Release]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Install ARM GCC toolchain
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-arm-none-eabi binutils-arm-none-eabi
        arm-none-eabi-gcc --version
    
    - name: Install CMake and Ninja
      run: |
        sudo apt-get install -y cmake ninja-build
        cmake --version
        ninja --version
    
    - name: Configure CMake (${{ matrix.build_type }})
      run: |
        cmake --preset ${{ matrix.build_type }}
    
    - name: Build
      run: |
        cmake --build build/${{ matrix.build_type }} --parallel
    
    - name: Show memory usage
      run: |
        arm-none-eabi-size build/${{ matrix.build_type }}/stm32-robotics-control.elf
        echo ""
        echo "Detailed size breakdown:"
        arm-none-eabi-size -A build/${{ matrix.build_type }}/stm32-robotics-control.elf
    
    - name: Generate build report
      run: |
        echo "## Build Report - ${{ matrix.build_type }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Memory Usage" >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        arm-none-eabi-size build/${{ matrix.build_type }}/stm32-robotics-control.elf >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Flash Usage" >> $GITHUB_STEP_SUMMARY
        FLASH_USED=$(arm-none-eabi-size build/${{ matrix.build_type }}/stm32-robotics-control.elf | tail -n 1 | awk '{print $1+$2}')
        FLASH_TOTAL=524288
        FLASH_PERCENT=$((FLASH_USED * 100 / FLASH_TOTAL))
        echo "- Used: ${FLASH_USED} bytes" >> $GITHUB_STEP_SUMMARY
        echo "- Total: ${FLASH_TOTAL} bytes (512 KB)" >> $GITHUB_STEP_SUMMARY
        echo "- Usage: ${FLASH_PERCENT}%" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### RAM Usage" >> $GITHUB_STEP_SUMMARY
        RAM_USED=$(arm-none-eabi-size build/${{ matrix.build_type }}/stm32-robotics-control.elf | tail -n 1 | awk '{print $2+$3}')
        RAM_TOTAL=131072
        RAM_PERCENT=$((RAM_USED * 100 / RAM_TOTAL))
        echo "- Used: ${RAM_USED} bytes" >> $GITHUB_STEP_SUMMARY
        echo "- Total: ${RAM_TOTAL} bytes (128 KB)" >> $GITHUB_STEP_SUMMARY
        echo "- Usage: ${RAM_PERCENT}%" >> $GITHUB_STEP_SUMMARY
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: firmware-${{ matrix.build_type }}
        path: |
          build/${{ matrix.build_type }}/stm32-robotics-control.elf
          build/${{ matrix.build_type }}/stm32-robotics-control.bin
          build/${{ matrix.build_type }}/stm32-robotics-control.hex
        retention-days: 30
    
    - name: Check for size increase
      if: github.event_name == 'pull_request'
      run: |
        echo "::notice::Build ${{ matrix.build_type }} successful. Check artifacts for firmware files."
